### ISSUE TITLE
Unable to access Notepad after Version 7.5.9 upgrade

### ISSUE THREAD

**Issue by adibas03** [mmtrt/notepad-plus-plus#11]
The version 7.5.9 upgrade happened on Nov 5, and since then, all the instances of Notepad stopped working.
Upon opening the `current` directory for the `notepad-plus-plus` snap, it is empty, with no file.
Tested fresh installation on alternate system with same environment, and had the same result.

OS: Ubuntu 18.0.4
Arch: amd64
Install: Fresh install and refresh install

**Comment by mmtrt** [comment]
Snap literally tells you below instructions when launch from command notepad-plus-plus because I have change wine base snap.

You need to connect this snap to the wine-platform snap.
```
snap disconnect notepad-plus-plus:wine-platform-plug
snap install wine-platform
snap connect notepad-plus-plus:wine-platform-plug wine-platform:wine-base-stable
```

**Comment by adibas03** [comment]
Did not realize it applied to update installations as well.
Will check now, and update.
Thanks
