### ISSUE TITLE
How to install plugin manager

### ISSUE THREAD

**Issue by gwarah** [mmtrt/notepad-plus-plus#13]
I'd like to install plugin manager to install others. Is there a way to install it by a snap command or any other  that avoid me put the plugins files directly in /snap/npp folder?

**Comment by mmtrt** [comment]
Not that I know though you can manually add plugin manager then install plugins from it.

**Comment by gwarah** [comment]
I believe it would be an interesting improvement: a way more secure and easy to load the plugin manager.

**Comment by mmtrt** [comment]
npp devs have entirely created new plugin manager called Plugin Admin in new update 7.6. 

https://notepad-plus-plus.org/features/plugin-admin.html

**Comment by gwarah** [comment]
Isn't it possible to load this plugin by menu? I've done it by menu command: `settings - import - import plugins`

After loaded, the npp suggested to update plugin manager. until now everything seems ok.

what I could see after these more recent updates of npp+ it changed to 64 bits, so some plugins are not  available.

**Comment by mmtrt** [comment]
Since version `7.6` npp uses `Plugin Admin` so I've push old build to `candidate` if you want to continue using older `Plugin Manager` though I don't use plugins so can't test each every.
Closing this.
