### ISSUE TITLE
Needs wine-platform installed, but doesn't depend on it

### ISSUE THREAD

**Issue by cslycord** [mmtrt/notepad-plus-plus#16]
At least on debian, after snapd is installed, if I immediately install the notepad-plus-plus snap, when I attempt to run it, it complains that it needs to be connected to the wine-platform snap. It would be preferable for the wine-platform snap to be automatically installed as a dependency, as the notepad-plus-plus snap requires it.

**Comment by mmtrt** [comment]
when npp snap installs for the first time after download then it connects the plugs so when it stuck on connecting necessary plugs there it auto downloads `wine-platform` snap then connects to it. Do note that wine-platform snap is large in size could take few moments to setup depend on user connection & system.

**Comment by cslycord** [comment]
When I installed the npp snap for the first time, any auto download/install
of wine-platform didn't occur.

**Comment by zhuker** [comment]
steps to reproduce:
```
git clone https://github.com/mmtrt/notepad-plus-plus.git
snapcraft snap
snap install --dangerous --devmode ./notepad-plus-plus_7.8.2_amd64.snap
notepad-plus-plus
```

error:
```
You need to connect this snap to the wine runtime snap.

You can do this with those commands:
snap install wine-platform-runtime
snap connect notepad-plus-plus:wine-runtime wine-platform-runtime
```

**Comment by mmtrt** [comment]
That's expected behavior on manual install of snap which won't connect nor download any of required snaps so users have to follow these steps defined.
