### ISSUE TITLE
npp launched thru terminal: shortcut "[ctrl] + [shift] + u" disabled

### ISSUE THREAD

**Issue by gwarah** [mmtrt/notepad-plus-plus#17]
**Scenario:** 

1. open a terminal 
2. run: `notepad-plus-plus &`
3. type a text with upper and lower chars and select it
4. type the shortcut: `[ctrl]+[shift]+u`

**Results**: The uppercase function is disabled and appears an `u char` out of the window

**My Configuration**

1. Npp debug information

```
Notepad++ v7.6.1   (64-bit)
Build time : Dec 12 2018 - 01:22:05
Path : Z:\home\luis\snap\notepad-plus-plus\171\notepad-plus-plus\notepad-plus-plus.exe
Admin mode : OFF
Local Conf mode : OFF
OS : Windows XP 64 bits (64-bit)
Plugins : ComparePlugin.dll DSpellCheck.dll mimeTools.dll NppConverter.dll NppExec.dll NppSnippets.dll 

```

2. Os information: `Linux  4.15.0-43-generic #46~16.04.1-Ubuntu SMP Fri Dec 7 13:31:08 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux`

**Screenshots**

![npp_ctrl_u_2019-01-16 10-43-27](https://user-images.githubusercontent.com/5703210/51253392-e16a7400-197c-11e9-8723-f72bc5ca1cc2.png)

**Comment by mmtrt** [comment]
works fine here, maybe the key combination already used by the OS?

**Comment by gwarah** [comment]
> works fine here, maybe the key combination already used by the OS?

I don't think it's caused by other shortcuts assigns. I've tested call npp by the desktop icon and no problem. I've also install npp in a VM and got the same problem.  Please, could you do the same above test calling npp by a terminal and by desktop icon?

**Comment by mmtrt** [comment]
I did tried to reproduce what you had done already then again I've tried it works fine every time both ways.
