### ISSUE TITLE
Can't open file using notepad++

### ISSUE THREAD

**Issue by erikdemarco** [mmtrt/notepad-plus-plus#19]
I'm using filezilla to work with my files and set notepad++ as my default editor. When I want to edit file it shows :

z:\tmp\folder\file.txt cannot be opened. folder 'z:\tmp\folder\' does't exist

All other text editor doesnt have this error.

Steps I tried:
-) enable 'read/write files on removable storage devices' from permission (it won't save the permission, just roll back to disabled)
-) try installing in classic mode (doesn't work)
sudo snap install notepad-plus-plus --classic
-) force enable permission via terminal: (doesn't work)
sudo snap connect snap-app:removable-media

maybe this is because you don't have 'file-system' plug? Because file that i want to access is in tmp folder

**Comment by mmtrt** [comment]
You can try bind mounting `tmp` to `home/tmp` inorder to get this working as the snap does not have access rights to / path so then work with your files from `$HOME/tmp`.

`mkdir $HOME/tmp`
`sudo mount -obind /tmp $HOME/tmp`

**Comment by erikdemarco** [comment]
Hello nice idea. but unfortunately it still doesnt work. 

Filezilla send this filepath to notepad++: 
'/tmp/file.txt'
not 
'$HOME/tmp/file.txt'

so notepad++ still gives this error:
'/tmp/file.txt' cannot be opened. folder '/tmp' does't exist

**Comment by mmtrt** [comment]
Other method I would suggest is install npp in system install wine. It would require install wine as per distro method.

**Comment by ThorsenRune** [comment]
> I'm using filezilla to work with my files and set notepad++ as my default editor. When I want to edit file it shows :
> 
> z:\tmp\folder\file.txt cannot be opened. folder 'z:\tmp\folder' does't exist
> 
> All other text editor doesnt have this error.
> 
> Steps I tried:
> -) enable 'read/write files on removable storage devices' from permission (it won't save the permission, just roll back to disabled)
> -) try installing in classic mode (doesn't work)
> sudo snap install notepad-plus-plus --classic
> -) force enable permission via terminal: (doesn't work)
> sudo snap connect snap-app:removable-media
> 
> maybe this is because you don't have 'file-system' plug? Because file that i want to access is in tmp folder

Same problem, lost my morning on this issue. It's a pity because NPP is great
