### ISSUE TITLE
Doesn't start on Fedora after the installation with Snapd

### ISSUE THREAD

**Issue by Warmuser** [mmtrt/notepad-plus-plus#2]
Fedora 27, latest updates and latest kernel.

**Comment by mmtrt** [comment]
Can you post output of these commands.
* snap version
* snap interfaces notepad-plus-plus

**Comment by Warmuser** [comment]
[xxxxxxx@localhost ~]$ snap interfaces notepad-plus-plus
Slot             Plug
:desktop         discographer,easy-disk-cleaner,notepad-plus-plus,speedy-duplicate-finder,wavebox,wordpress-desktop
:desktop-legacy  discographer,easy-disk-cleaner,notepad-plus-plus,speedy-duplicate-finder,wavebox
:home            deepin-image-viewer,discographer,easy-disk-cleaner,imagenes,notepad-plus-plus,speedy-duplicate-finder,ultimate-media-downloader2,wavebox,wordpress-desktop
:network         deepin-image-viewer,discographer,easy-disk-cleaner,imagenes,notepad-plus-plus,speedy-duplicate-finder,ultimate-media-downloader2,wavebox,wordpress-desktop
:opengl          deepin-image-viewer,discographer,easy-disk-cleaner,imagenes,notepad-plus-plus,speedy-duplicate-finder,ultimate-media-downloader2,wavebox,wordpress-desktop
:wayland         notepad-plus-plus,wavebox,wordpress-desktop
:x11             deepin-image-viewer,discographer,easy-disk-cleaner,imagenes,notepad-plus-plus,speedy-duplicate-finder,wavebox,wordpress-desktop
-                notepad-plus-plus:cups-control
-                notepad-plus-plus:hardware-observe
-                notepad-plus-plus:process-control
-                notepad-plus-plus:removable-media

**Comment by Warmuser** [comment]
Ok, thanks!
