### ISSUE TITLE
Clipboard randomly fails in v7.8.1 64 bit 

### ISSUE THREAD

**Issue by klei1984** [mmtrt/notepad-plus-plus#21]
After upgrading to Ubuntu 19.10 from 19.04, NPP installed via Snap upgraded itself to v7.8.1 64 bit.

Since then ctrl+c, mouse context menu copy sporadically fails/rarely works. Issue is present between NPP tabs and NPP to external applications. External application to NPP always works reliably. Editing text within NPP tab like ctrl+d to duplicate line or simple keyboard operations work reliably.
Is there a way to install an older revision to see since when the issue had been introduced or whether NPP is the root cause at all?

**Comment by mmtrt** [comment]
If old snap version exists then this should revert back to it.

`snap revert notepad-plus-plus`

**Comment by klei1984** [comment]
Thanks for the info. I was able to revert back to v7.8, but it behaves the same way. I have a system backup from before the OS upgrade. I will check it out tomorrow what was the NPP version that worked before.

**Comment by klei1984** [comment]
So under Ubuntu 19.04, with wine-4.0.2, NPP v7.8.1 64 bit works flawlessly. It seems the problem I face is related to Ubuntu 19.10.
Snap related version info is as follows:
snap    2.42.1
snapd   2.42.1
series  16
ubuntu  19.04
kernel  5.0.0-36-generic

**Comment by klei1984** [comment]
My issue is related to the desktop server. Under Ubuntu (Xorg) and Ubuntu (Wayland) the favorites side bar has some glitches on mouse hover events and clipboard for NPP does not work reliably. If i use GNOME Flashback (metacity) NPP works without issues and desktop widgets show no glitches and the likes. I will try to fix the desktop server issues.
