### ISSUE TITLE
Foreign characters e.g. chinese not displayed correctly

### ISSUE THREAD

**Issue by OzzieIsaacs** [mmtrt/notepad-plus-plus#22]
Thank you for bringing my favorite windows editor to Linux. 
In the most recent version 7.8.4 I've encountered an problem, while opening files with chinese characters these characters are only displayed as rectangcles.
![image](https://user-images.githubusercontent.com/6438895/75620549-6a953800-5b8a-11ea-98f3-1a7c3782e830.png)
whereas this characters (执一) are display in other editors correct:
![image](https://user-images.githubusercontent.com/6438895/75620571-99131300-5b8a-11ea-9c91-557597c8d317.png).
I'm not sure, but I this this working in the previous version. 
Systeminformation:
snap       2.43.3
snapd      2.43.3
series     16
linuxmint  19.3
kernel     5.3.0-40-generic
I've installed the following snaps:
```
core                    16-2.43.3                   8689  stable        canonical✓   core
core18                  20200124                    1668  stable        canonical✓   base
gnome-3-28-1804         3.28.0-16-g27c9498.27c9498  116   stable        canonical✓   -
gtk-common-themes       0.1-28-g1503258             1440  stable        canonical✓   -
notepad-plus-plus       7.8.4                       223   stable        mmtrt        -
pycharm-community       2019.3.3                    179   stable        jetbrains✓   classic
snap-store              20191114.a9948d5            209   stable        canonical✓   -
traefik-nacc            1.0.1                       2     edge          nacc         -
wine-platform           3.0.4-4.6                   128   stable        mmtrt        -
wine-platform-3-stable  3.0.4                       6     stable        mmtrt        -
wine-platform-i386      1.0                         25    stable        mmtrt        -
wine-platform-runtime   v1.0                        89    stable        mmtrt        -
```

**Comment by mmtrt** [comment]
Can you tell me output of these command

`locale | grep -e 'LANG=zh_CN' -e 'LANG=zh_SG'`

`locale | grep -e 'LANG=zh_HK' -e 'LANG=zh_MO' -e 'LANG=zh_TW'`

Also tell which `cjk` font mint uses.

**Comment by OzzieIsaacs** [comment]
The only locale on my system is de_De. So the output of both commands is empty.
(Normal terminal output. Should'n it depend somehow on installed fonts in the wine runtime? I don't know how to get this information). 

Cjk I'm not sure about, package manager outputs this 2 installed fonts after searching for `cjk` beside some other not installed programms with cjk in the name.
![grafik](https://user-images.githubusercontent.com/6438895/75621423-6ff78000-5b94-11ea-97dc-609ed0d6e8d1.png)

**Comment by mmtrt** [comment]
Currently I use these checks for user current locale following then add changes to registry for cjk font if one of these comes up on first time setting up wineprefix.

```
locale | grep -e 'LANG=zh_CN' -e 'LANG=zh_SG'

locale | grep -e 'LANG=zh_HK' -e 'LANG=zh_MO' -e 'LANG=zh_TW'
```

**Comment by OzzieIsaacs** [comment]
![grafik](https://user-images.githubusercontent.com/6438895/75621580-83a3e600-5b96-11ea-8820-49902e1c0ad1.png)
I managed it to start a console from notepad++ (Excecute - external program and then cmd). There I could start the wine included writer. The "Noto" fonts are displayed there:
![grafik](https://user-images.githubusercontent.com/6438895/75621594-b4841b00-5b96-11ea-9263-7783781eeaa5.png)
And if I change the font to a right one can enter chinese characters.

**Comment by mmtrt** [comment]
Yeah defualt font does not support `cjk` text.

**Comment by OzzieIsaacs** [comment]
So what would be a solution, is it possible to install and use a fully unicode support font and use it as default font in notepad++?

**Comment by OzzieIsaacs** [comment]
Just to make it clear: my problem is files with foreign characters are not displayed correct, not the menus in notepad++

**Comment by mmtrt** [comment]
You can try adding font to `$HOME/snap/notepad-plus-plus/common/.wine/drive_c/windows/fonts` then change font in npp settings.

**Comment by OzzieIsaacs** [comment]
Thanks. I tried it. 
I found code2000 (http://www.alanwood.net/downloads/) or the gnu unicodefont (http://unifoundry.com/unifont/index.html) are suitable, they contain the characters I need (at least chinese and khmer). 
Maybe it would be an idea to write some sentences in the wiki, so the next who has the problem can find a solution.
