### ISSUE TITLE
Cannot open files from /data directory

### ISSUE THREAD

**Issue by pac0007** [mmtrt/notepad-plus-plus#23]
I am using Ubuntu 16.04.
I couldn't open files using notepad++ from /data.
notepad++ doesn't recognize /data directory.

Here is my environment info
notepad-plus-plus       7.8.5  Rev227
wine-platform-3-stable  3.0.4 Rev6
wine-platform-runtime   v1.0 Rev104

The permissions of /data are
drwxrwxrwx   7 root root 4.0K Feb 28 15:59 data
drwxr-xr-x   8 root root 4.0K May  6  2019 home

home also have the same permissions but able to access the files from /home but not from /data

**Comment by mmtrt** [comment]
it has permission for home path but it doesn't for other folder that resides on root path due to strict confinement.

You can try bind mount that data dir in home see if it works.

**Comment by pac0007** [comment]
Thanks for the info, bind mount is working.
Is there any way for the notepad++ to give permissions to access other folders. If the solution is to install wine and notepad++ separately without snap, I am OK to follow this approach. Can you please share me the instructions.

**Comment by mmtrt** [comment]
install wine from winehq 
https://wiki.winehq.org/Download
then download and install npp.
