### ISSUE TITLE
cannot install offline

### ISSUE THREAD

**Issue by vin-d** [mmtrt/notepad-plus-plus#24]
the same as this happens :
https://askubuntu.com/questions/761742/is-it-possible-to-install-the-snap-application-in-an-offline-computer#comment1707969_944479
```
$ sudo snap install --dangerous notepad-plus-plus_232.snap 
error: cannot perform the following tasks:
- Ensure prerequisites for "notepad-plus-plus" are available (Post https://api.snapcraft.io/v2/snaps/refresh: dial tcp: lookup api.snapcraft.io: no such host)
```
how to bypass the prerequisites ?

**Comment by mmtrt** [comment]
This snap depends on these snaps so you have to install them first then `npp` snap.

`wine-platform-runtime`
`wine-platform-5-stable`
`gtk-common-themes`
