### ISSUE TITLE
Clipboard is failing alternately

### ISSUE THREAD

**Issue by gwarah** [mmtrt/notepad-plus-plus#25]
# Scenario

1. Open npp with 2 file tabs with clipboard panel open. The windows title appears [administrator] (??)
2. Alternately  I've copy one line at time from the first tab to the second one
3. The clipboard panel shows the correct history but `[ctrl]+v` doesn't work alternately

# Environment
- ubuntu 20.04
- notepad-plus-plus       7.8.9 - 238   latest/stable
- connections

```
snap connections notepad-plus-plus
Interface               Plug                                Slot                                  Notes
content[icon-themes]    notepad-plus-plus:icon-themes       gtk-common-themes:icon-themes         -
content[wine-5-stable]  notepad-plus-plus:wine-5-stable     wine-platform-5-stable:wine-5-stable  -
content[wine-runtime]   notepad-plus-plus:wine-runtime      wine-platform-runtime:wine-runtime    -
cups-control            notepad-plus-plus:cups-control      -                                     -
desktop                 notepad-plus-plus:desktop           :desktop                              -
desktop-legacy          notepad-plus-plus:desktop-legacy    :desktop-legacy                       -
hardware-observe        notepad-plus-plus:hardware-observe  -                                     -
home                    notepad-plus-plus:home              :home                                 -
network                 notepad-plus-plus:network           :network                              -
opengl                  notepad-plus-plus:opengl            :opengl                               -
process-control         notepad-plus-plus:process-control   -                                     -
removable-media         notepad-plus-plus:removable-media   :removable-media                      manual
wayland                 notepad-plus-plus:wayland           :wayland                              -
x11                     notepad-plus-plus:x11               :x11                                  -


```
![npp01](https://user-images.githubusercontent.com/5703210/88412033-522eef80-cdaf-11ea-8d03-070a5bbb0af3.jpg)
![npp02](https://user-images.githubusercontent.com/5703210/88412034-52c78600-cdaf-11ea-8b92-033e7e496a2b.jpg)
![npp03](https://user-images.githubusercontent.com/5703210/88412036-53601c80-cdaf-11ea-9d01-8bcd89f5f7e3.jpg)
![npp04](https://user-images.githubusercontent.com/5703210/88412038-53f8b300-cdaf-11ea-9103-edcef704f0b3.jpg)
![npp05](https://user-images.githubusercontent.com/5703210/88412040-53f8b300-cdaf-11ea-850a-f35bffc71cc1.jpg)
![npp_freezing](https://user-images.githubusercontent.com/5703210/88412043-54914980-cdaf-11ea-80e6-117804369467.jpg)

# tail -f /var/log/syslog

![tail_f](https://user-images.githubusercontent.com/5703210/88412045-54914980-cdaf-11ea-99b9-92444b4a6794.jpg)

**Comment by mmtrt** [comment]
I couldn't reproduce issue works fine here, can you post results of these so I could try to replicate the issue,

* `locale`
* `localectl`

**Comment by gwarah** [comment]
```
~$ locale
LANG=pt_BR.UTF-8
LANGUAGE=pt_BR:pt:en
LC_CTYPE="pt_BR.UTF-8"
LC_NUMERIC="pt_BR.UTF-8"
LC_TIME="pt_BR.UTF-8"
LC_COLLATE="pt_BR.UTF-8"
LC_MONETARY="pt_BR.UTF-8"
LC_MESSAGES="pt_BR.UTF-8"
LC_PAPER="pt_BR.UTF-8"
LC_NAME="pt_BR.UTF-8"
LC_ADDRESS="pt_BR.UTF-8"
LC_TELEPHONE="pt_BR.UTF-8"
LC_MEASUREMENT="pt_BR.UTF-8"
LC_IDENTIFICATION="pt_BR.UTF-8"
LC_ALL=

~$ localectl
   System Locale: LANG=pt_BR.UTF-8
                  LANGUAGE=pt_BR:pt:en
       VC Keymap: n/a
      X11 Layout: br
       X11 Model: pc105

~$ env | grep LC
~$

```

**Comment by gwarah** [comment]
Uptdating: foobar2k has the same behavior .... maybe the problem could be an wine component

**Comment by mmtrt** [comment]
can you try npp build from edge see if this fixes this issue for you,

**Comment by gwarah** [comment]
@mmtrt  I fix this issue \o/

Desinstall all mmtrt packages (with `--purge`), including wine*, and then install npp and foobar2k again. I believe it was some issue related to wine* packages.
