### ISSUE TITLE
an issue which is more of a help request

### ISSUE THREAD

**Issue by ineuw** [mmtrt/notepad-plus-plus#26]
Is it possible to increase the "skin" font-size? 
![200820-notepadpp skin](https://user-images.githubusercontent.com/10367016/90792573-a2c73900-e2d8-11ea-9f80-6890def8a5ba.png)

**Comment by mmtrt** [comment]
Yes, check similar issue #7

**Comment by ineuw** [comment]
An emoji is not a sufficient thank you. So, I repeat my thanks in writing as well. The 120 dpi setting is perfect. This also means that the font size in the Style Configurator needs be adjusted accordingly, which is not a problem.
