### ISSUE TITLE
Option for HiDPI display 

### ISSUE THREAD

**Issue by finddabug** [mmtrt/notepad-plus-plus#27]
I am running notepad-plus-plus on a High-DPI Monitor in Ubuntu 20.10 but the fonts and menu bars are all to small. I tried to start the snap package with the option: 
`/snap/bin/notepad-plus-plus --force-device-scale-factor=2 %F `  but it has no effect.
On a native WINE installation it is possible to run winecfg and change the resolution but I use the wine-platform-5-stable and winecfg is not available.
Is there a fix for this?

**Comment by mmtrt** [comment]
it should run winecfg with this command

`notepad-plus-plus.wine winecfg`

**Comment by Brog33** [comment]
Finally. Been trying for hours to figure out how to launch the winecfg for this snap. You really should mention it in the documentation cos entering "notepad-plus-plus winecfg" only creates a text file called winecfg ;)

**Comment by finddabug** [comment]
Worked just fine :-) Thx a bunch
