### ISSUE TITLE
Wine is recognised as virus

### ISSUE THREAD

**Issue by galgalesh** [mmtrt/notepad-plus-plus#28]
I just wanted to get your attention to an issue posted on Reddit. Apparently, Wine binaries like `arp.exe` are seen as a virus by some anti-virus software. Some examples:

* https://www.virustotal.com/gui/file/e1ed3a01ca190c30de77c5f8d5efc7c8e437f0cafd76ef9a59c8bb961af2f682/detection
* https://www.virustotal.com/gui/file/c72f7b648feae97f85809e415e967c9d6aaf29525c65ba1dfff71673cc4da1ae/detection

The AV was "Blackberry Cylance" on Ubuntu 18.04.5 LTS.

Is there anything we can do to prevent this? Do you know how Wine shipped with Ubuntu solves this?

source: https://www.reddit.com/r/linux/comments/ofeox9/snap_notepadplusplus_malware/

**Comment by mmtrt** [comment]
There is nothing we can do as these are false positives.

Last year in December I received mail from Igor Ljubuncic who works at canonical that wine stable 5 snap had malware result was this from Sophos scan .


```
 Virus 'Mal/Generic-S' found in file /snap/wine-platform-5-stable/12/opt/wine-stable/lib/wine/ngen.exe
Virus 'Mal/Generic-S' found in file /snap/wine-platform-5-stable/12/opt/wine-stable/lib/wine/powershell.exe
Virus 'Mal/Generic-S' found in file /snap/wine-platform-5-stable/12/opt/wine-stable/lib/wine/regasm.exe
Virus 'Mal/Generic-S' found in file /snap/wine-platform-5-stable/12/opt/wine-stable/lib/wine/regini.exe
Virus 'Mal/Generic-S' found in file /snap/wine-platform-5-stable/12/opt/wine-stable/lib/wine/regsvcs.exe
Virus 'Mal/Generic-S' found in file /snap/wine-platform-5-stable/12/opt/wine-stable/lib/wine/sdbinst.exe

```

In the end we had contact with wine devs individually regarding this issue and their response was that these are false positives nothing to worry about.

**Comment by mmtrt** [comment]
Since `WINE` devs started changing its library files `*.exe.so` to `PE` then I guess these `*.exe` files are still being flagged false positives. I've just checked from `Arch Linux` on my main machine `wine` installed from official repos `multilib/wine 6.12-1 [installed]` still these files `tasklist.exe` `arp.exe` are detected as malware.
