### ISSUE TITLE
Cannot increase NPP menu font size

### ISSUE THREAD

**Issue by simurq** [mmtrt/notepad-plus-plus#29]
My system is Pop OS 21.04. However, the tab menu font size is too small to read. Is it possible to increase font size? I've not found any option under NPP Preferences either. I've read the similar issue #7 but running `notepad-plus-plus winecfg` from the terminal opens NPP with a new winecfg file instead, not a GUI, as on the image.

I don't have Wine installed, by the way.

Thanks! And a special thank you for snapcrafting NPP for Linux!

**Comment by mmtrt** [comment]
`notepad-plus-plus.wine winecfg` should open it.

**Comment by simurq** [comment]
Thank you very much, it worked!
