### ISSUE TITLE
Access violation error on "Preferences..." and "Style Configurator..." menus 

### ISSUE THREAD

**Issue by jcahigal** [mmtrt/notepad-plus-plus#36]
![image](https://user-images.githubusercontent.com/4038993/183579883-65a60eb5-de82-4a15-b115-79228ce6b517.png)
I get this error always that I choose one of these menu entries.

I have notepadd++ installed on Ubuntu 22.04.1 LTS, as a snap application

**Comment by mmtrt** [comment]
94a86c51fc41b394b9628de4d8f9dc144ebce596 fixes this issue.
