### ISSUE TITLE
what's the point of doing snap which emulates a program under wine when there is an equivalent in qt?

### ISSUE THREAD

**Issue by andykimpe** [mmtrt/notepad-plus-plus#38]
what is the point of creating a version of notepad++ to emulate in wine and which will be much slower than a hard code program in snap when there is notepadqq which has a 99% similar interface with the functions and which develops in qt ?

and who of course and already present on snap

https://github.com/notepadqq/notepadqq

`sudo snap install notepadqq`

**Comment by TheSchmed** [comment]
Hi `andykimpe`, 2 things I would note:
1. This is not an "issue", it is fine to release similar software, if you don't want to use it it is OK.
2. I believe notepadqq does not support installation of plugins, whereas I can easily set up plugins like `NPPFTP` right away in this app. So yes, there are features differences.

**Comment by mmtrt** [comment]
it works for users that are familiar with so it doesn't matters as long as it does the job.
