### ISSUE TITLE
I cat't launch notepad-plus-plus in ubantu 22.04, app version is 8.6.5

### ISSUE THREAD

**Issue by Martine1993** [mmtrt/notepad-plus-plus#39]
$ notepad-plus-plus

Installing application..
Running hook '/snap/notepad-plus-plus/400/sommelier/hooks/pre-install'
Starting application..
wine: failed to open "/home/martine/snap/notepad-plus-plus/400/notepad-plus-plus/notepad-plus-plus.exe": c0000135

**Comment by armanexplorer** [comment]
Same for me on Debian 12. It seems npp has been broken in some way like [this](https://forum.snapcraft.io/t/notepad-broken/31651) in 2022

**Comment by mmtrt** [comment]
fixed the issue it should be working now on latest update.
