### ISSUE TITLE
Special characters on keyboard not recognized

### ISSUE THREAD

**Issue by marius-wieschollek** [mmtrt/notepad-plus-plus#4]
I just installed the app from the Ubuntu Software store on Ubuntu 18.04.
I'm using a Keyboard with a german layout. while the standard keys work just fine, any special character such as `Ä`, `Ö`, `Ü`, `ß` do not work. Also combined characters like `é` ("´" + "e") do not work either.
Copy and paster just works fine.

**Comment by mmtrt** [comment]
do these work on normal wine install notepad++ aside from this snap.

**Comment by marius-wieschollek** [comment]
yes, i have currently a working notepad++ installed with wine-stable.

**Comment by mmtrt** [comment]
thanks for confirming, will debug this issue over weekend no promises though.

**Comment by marius-wieschollek** [comment]
:+1:

**Comment by mmtrt** [comment]
fix bf00a8a48b952638eed7cd0172689b0e39a93e79 is live on `edge` channel so snap build `7.5.6 (49)` should work please test it.

To update snap from edge
* `sudo snap refresh notepad-plus-plus --edge`

**Comment by marius-wieschollek** [comment]
The new build works fine for `Ä`, `Ö`, `Ü`, `ß` but composed letters like `ê` (`^` + `e`) do still not work.

**Comment by mmtrt** [comment]
test build `7.5.6 (53)` on edge

**Comment by marius-wieschollek** [comment]
:+1: Great. Now all keys work perfectly. Thanks for your help.
