### ISSUE TITLE
Release 8.6.6 not working for Ubuntu 22.04.4 LTS

### ISSUE THREAD

**Issue by khushali04** [mmtrt/notepad-plus-plus#41]
While clicking on the icon, nothing happens.
This is the response i get when i am trying to open from terminal.

$ notepad-plus-plus
Installing application..
Running hook '/snap/notepad-plus-plus/403/sommelier/hooks/pre-install'
Starting application..
wine: failed to open "/home/user/snap/notepad-plus-plus/403/notepad-plus-plus/notepad-plus-plus.exe": c0000135

**Comment by ahmedmoselhi** [comment]
same here on opensuse tumbleweed

**Comment by mmtrt** [comment]
issue is fixed now.
