### ISSUE TITLE
Add support for x86_64 architecture

### ISSUE THREAD

**Issue by vickael** [mmtrt/notepad-plus-plus#5]
Notepad++ with support x86_64 architecture through wine.

For exemple, use this source for Wine
https://dl.winehq.org/wine-builds/ubuntu/pool/main/wine-stable-amd64_3.0.1~xenial_amd64.deb

And this for the Notepad++
https://notepad-plus-plus.org/repository/7.x/7.5.6/npp.7.5.6.bin.x64.7z

I'm sorry about my English, it is rusty.

**Comment by mmtrt** [comment]
I know about it even before creating this snap though using `x86_64` packages only will kill the support for `i386` linux distros so many users out there still use such systems but still if `notepad++` dev decides to stop creating `x86` builds then sure I will stop building it as well till then I see no reason to stop it.

Thanks for your suggestion.

**Comment by mmtrt** [comment]
push x64 build on snap edge branch so try it.

`snap install notepad-plus-plus --edge`

**Comment by Vyskael** [comment]
Thanks for the x64 support.
