### ISSUE TITLE
GUI font too small when scaling - not consistent with display scaling

### ISSUE THREAD

**Issue by orfeonomia** [mmtrt/notepad-plus-plus#7]
I use Ubuntu with display scaling 200% (14-inch display, 2560x1440pix so the pixel density is relatively high: more than 183 pix/inch or 70 pix/mm).
When I run Notepad Plus Plus the app doesn't scale as the rest of my display. All GUI elements are much too small to be readable. So the application is effectively unusable (although technically fully functional). I just have to use magnifying lens to use it (and this is not a joke: I actually use Zoom - a part of Accessibility options).

I can use CTRL+MOUSE_WHEEL to increase text area font size but I can't increase GUI itself (menus, button captions etc.) font size.

I think Notepad should take display scaling into account, not only display resolution.
Is there anything I can do to adjust Notepad to my system (and not my system to Notepad)?
Of course, decreasing screen resolution works and helps, but it degrades the rest of my system. I need to keep it high for other external displays.

**Comment by mmtrt** [comment]
does scaling work for you on normal wine install of notepad-plus-plus aside from this snap.

**Comment by orfeonomia** [comment]
I don't know because I don't have Wine installed on my system.
apt list --installed | grep wine
returns nothing.
If it may help, I can share some config files or provide a screenshot

**Comment by mmtrt** [comment]
no need just run this `notepad-plus-plus winecfg` command on terminal then click on graphics tab select dpi 
![wine configuration_001](https://user-images.githubusercontent.com/2322598/42487239-86141c12-8419-11e8-823a-644c2b356718.png)

**Comment by orfeonomia** [comment]
I don't know because I don't have Wine installed on my system.
apt list --installed | grep wine
returns nothing.
If it may help, I can share some config files or provide a screenshot

**Comment by orfeonomia** [comment]
OK, it helped. I didn't know I can get an access to underlying WineHQ.
Thank you for the help
