### ISSUE TITLE
Only English input works

### ISSUE THREAD

**Issue by Max1mCom** [mmtrt/notepad-plus-plus#9]
Hello,

After last update I cannot typing Russian, only English.

└──╼ $snap run notepad-plus-plus
error: Z:\home\max\snap\notepad-plus-plus\124\notepad-plus-plus\plugins\Config\Hunspell\en_US.usr: cannot open

**Comment by mmtrt** [comment]
fix has been pushed to wine-platform snap.

To update snap

`snap refresh`

Closing this issue.

**Comment by Max1mCom** [comment]
Doesn't work:

└──╼ $snap refresh
All snaps up to date.
┌─[max@parrot]─[~]
└──╼ $snap list | grep notepad-plus-plus
notepad-plus-plus   7.5.9                   124   stable    mmtrt             -

**Comment by Max1mCom** [comment]
Oh, I'm sorry. I forgot to relaunch notepad. It's working now, thanks!
